Pagination for items and dates
clarify/pyclarify pull request #74
Opened 2022-01-26 15:02 UTC by AlexiaArtemis

Items: The limit can now be over 50.
notBefore, before: The window can also now be longer than 960 hours.

2022-01-27 10:33 UTC, oddaspa requested changes
There is a lot going on here. I think we should go through it together. I would also like to see some tests on the iterables.

2022-01-27 10:33 UTC, oddaspa commented on src/pyclarify/__utils__/pagination.py
> +            raise StopIteration
Im a bit unsure of the logic here. Is there a need to have the `count_iter` variable? In the closing `elif` why do we check that `self.count_remainder == 0`?

2022-01-27 10:33 UTC, oddaspa commented on src/pyclarify/client.py
> +        item_iter = iter(get_item)
No need to call `iter` on the iterable object.

2022-01-27 10:33 UTC, oddaspa commented on src/pyclarify/client.py
> +                    before = datetime_to_str(before)
Can these be inside the iterator?

2022-01-27 10:33 UTC, oddaspa commented on src/pyclarify/client.py
> -                >>>        "item_id_sum": [0.0, 0.0]
Why remove this?

2022-01-27 10:33 UTC, oddaspa commented on src/pyclarify/models/requests.py
> +LimitSelectItems = conint(ge=0)
We might need to rethink how we are creating requests

2022-01-27 10:33 UTC, oddaspa commented on src/pyclarify/client.py
> +        return responses
If there is a singe error in all of the responses it will break.

2022-01-27 11:53 UTC, AlexiaArtemis commented on src/pyclarify/__utils__/convert.py
> +    return date
I added this before I did rebase on dev. This branch is still been worked on. I will check if I can use the other methods in this file. 👍

2022-01-27 11:55 UTC, AlexiaArtemis commented on src/pyclarify/client.py
> +from curses import KEY_SLEFT
No idea 😛 Something weird from the rebase maybe. will remove it

2022-01-27 11:56 UTC, AlexiaArtemis commented on src/pyclarify/__utils__/pagination.py
> +            self.hours = self.get_hours(self.not_before, self.before)
Yes I think this is needed. Will double check.

2022-01-27 11:57 UTC, AlexiaArtemis commented on src/pyclarify/__utils__/pagination.py
> +            raise StopIteration
So that it can not enter twice. For now this all is working as expected but I am still working on making it look nice

2022-01-27 12:00 UTC, AlexiaArtemis commented on src/pyclarify/client.py
> +        item_iter = iter(get_item)
The get_item object is iterable, because we can get an iterator from it. The iter() function return an iterator.

2022-01-27 12:03 UTC, AlexiaArtemis commented on src/pyclarify/client.py
> -                >>>        "item_id_sum": [0.0, 0.0]
Hm did not do it on purpose, happened from the rebase probably.

2022-01-27 12:04 UTC, AlexiaArtemis commented on src/pyclarify/client.py
> +        return responses
Yeah probably. Have not finished this

2022-01-27 12:26 UTC, AlexiaArtemis commented on src/pyclarify/__utils__/pagination.py
> +class GetItems:
This task was originally only for items and dates. Once we work on the signals, we can see how we can combine it.

2022-02-01 13:15 UTC, oddaspa requested changes

2022-02-01 13:15 UTC, oddaspa commented on tests/data/mock-select-items.json
> -          "rollup": "PT1H"
Why remove the rollup?

2022-02-01 13:15 UTC, oddaspa commented on tests/test_pagination.py
> +class TestClarifyClientSelectItems(unittest.TestCase):
Update class name

2022-02-01 13:15 UTC, oddaspa commented on src/pyclarify/client.py
> +    errors = errors + (err,)
Needs to be inside `else` condition

2022-02-01 13:16 UTC, AlexiaArtemis commented on tests/data/mock-select-items.json
> -          "rollup": "PT1H"
To see how it works without it. The output is different

2022-02-01 13:26 UTC, oddaspa commented on tests/data/mock-select-items.json
> -          "rollup": "PT1H"
Then I would duplicate, not remove.

2022-02-02 12:11 UTC, oddaspa commented
Can you also update the `send` method in ClarifyClient to use the pagination method?

2022-02-02 12:17 UTC, AlexiaArtemis commented
Hm I have already... Do you mean [this](https://github.com/clarify/pyclarify/blob/9cc8757d51a6e5268b8f342106285efca5e82a03/src/pyclarify/client.py#L944) for example?

2022-02-02 15:17 UTC, AlexiaArtemis commented
Yes I agree @zehsilva.  I also think that we can improve it in the future.

2022-02-02 15:19 UTC, merged